Repository vmware/vsphere-automation-sdk-python, pull requests merged in 2018-06, with the labels that each got.

#67 add deploy ovf template in cloud sddc sample
  samples/vmc/sddc/deploy_ovf_template.py
Labels: sample

#64 README for doc folder
  doc/README.md
Labels: dco-required, enhancement

#73 Updated VMC Readme
  samples/vmc/README.md
Labels: dco-required

#74 dict.itervalues is deprecated in Python3. Fixing sample
  samples/vsphere/backuprestore/backup_job_list.py
Labels: dco-required

#75 add account linking config when creating sddc
  README.md
  samples/vmc/sddc/sddc_crud.py
Labels: dco-required

#78 A sample to list the Services in the vCenter Server. Signed-off-by:jo…
  samples/vsphere/services/services_list.py
Labels: dco-required
